### ISSUE TITLE
Problems import to influxdb

### ISSUE THREAD

**Issue by cayetano** [jojohappy/zabbix-relay#11]
Hi,

I have a problen all time has this error:
start relay
Total 112 hosts
/root/zabbix-relay-master/lib/adapter/influxdbAdapter.js:11
    host: result[3],
                ^

TypeError: Cannot read property '3' of null
    at new InfluxdbAdapter (/root/zabbix-relay-master/lib/adapter/influxdbAdapter.js:11:17)
    at /root/zabbix-relay-master/lib/relay.js:44:25
    at Array.forEach (native)
    at /root/zabbix-relay-master/lib/relay.js:43:25
    at null.<anonymous> (/root/zabbix-relay-master/node_modules/zabbix-node/lib/zabbix.js:27:9)
    at null.<anonymous> (/root/zabbix-relay-master/node_modules/zabbix-node/lib/zabbix.js:66:5)
    at Request.self.callback (/root/zabbix-relay-master/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/zabbix-relay-master/node_modules/request/request.js:1171:10)

Thanks

Regads, Cayetano.

**Comment by jojohappy** [comment]
Pls provide your influxdb url string, maybe zabbix-relay can not parse it, thank you!

**Comment by cayetano** [comment]
OK , this is the solution. My influx has no credential to logon it. the
is http://@localhost:8086/import , and ... it work !!!!!
A
One other question:
I'm use :
node server.js command -g '<groupname>' -s influx  -l 10m -u
'http://@localhost:8086/import'
-d influxdb -t history
To include data from one group.

And .. for any group ?

node server.js command -g '' -s influx  -l 10m -u
'http://@localhost:8086/import'
-d influxdb -t history
node server.js command -g '*' -s influx  -l 10m -u
'http://@localhost:8086/import'
-d influxdb -t history
node server.js command -g '%' -s influx  -l 10m -u
'http://@localhost:8086/import'
-d influxdb -t history

Not work

Regards
Cayetano

2017-06-14 5:00 GMT+02:00 Michael Dai <notifications@github.com>:

**Comment by ghost** [comment]
Hi I have the exact same issue.

node server.js command -g 'Development' -t history -d influxdb -l 10m -u http://localhost:8086/zabbix -s influx
start relay
Total 3 hosts
/root/install/zabbix-relay/lib/adapter/influxdbAdapter.js:11
    host: result[3],
                ^

**Comment by ghost** [comment]
Discard last post, it only works if you have a user created in influxdb and use that one.
