### ISSUE TITLE
Unable to extract information from Zabbix version 3.4

### ISSUE THREAD

**Issue by FICR** [jojohappy/zabbix-relay#13]
Hi I´m getting error below:

zabbix-relay/lib/relay.js:40

      var length = hostgroup.hosts.length;
                                    ^

TypeError: Cannot read property 'length' of undefined
    at /etc/relay_zabix_elastic/1/zabbix-relay/lib/relay.js:40:37
    at Client.<anonymous> (/etc/relay_zabix_elastic/1/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:19:7)
    at Client.<anonymous> (/etc/relay_zabix_elastic/1/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:66:5)
    at Request.self.callback (/etc/relay_zabix_elastic/1/zabbix-relay/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/etc/relay_zabix_elastic/1/zabbix-relay/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/etc/relay_zabix_elastic/1/zabbix-relay/node_modules/request/request.js:1083:12)

Any help will be appreciated

**Comment by FICR** [comment]
this is my CLI 

node server.js command -d elastic -g 'Zabbix servers' -p '2019-05-09|2019-05-10' -t 'history' -u 'http://XXXXXXX:9200'
