### ISSUE TITLE
Error: Cannot enqueue Query after fatal error

### ISSUE THREAD

**Issue by mayankdtu** [jojohappy/zabbix-relay#3]
Hi,
Thanks for the useful tool.

I keep getting an error when I try to export my zabbix data to influxdb. Do you have any idea why this issue might be present.

> Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/mayank/zabbixRelay/zabbix-relay/node_modules/mysql/lib/protocol/Protocol.js:199:16)
    at Protocol._enqueue (/home/mayank/zabbixRelay/zabbix-relay/node_modules/mysql/lib/protocol/Protocol.js:135:13)
    at Connection.query (/home/mayank/zabbixRelay/zabbix-relay/node_modules/mysql/lib/Connection.js:214:25)
    at fetchTrends (/home/mayank/zabbixRelay/zabbix-relay/lib/task.js:43:41)
    at /home/mayank/zabbixRelay/zabbix-relay/lib/task.js:72:9
    at Array.forEach (native)
    at /home/mayank/zabbixRelay/zabbix-relay/lib/task.js:71:13
    at .<anonymous> (/home/mayank/zabbixRelay/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:27:9)
    at .<anonymous> (/home/mayank/zabbixRelay/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:66:5)
    at Request.self.callback (/home/mayank/zabbixRelay/zabbix-relay/node_modules/zabbix-node/node_modules/request/request.js:187:22) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }

**Comment by jojohappy** [comment]
Hi @mayankdtu 

Could you provide more information, such as your execute command, zabbix version and node_mysql version. Those can help us to find problem.

**Comment by mayankdtu** [comment]
Hey @jojohappy , I found the problem, it was an error while installation of a module. I copied everything again  and it worked fine, 
Thanks
