### ISSUE TITLE
Error in importing historical data

### ISSUE THREAD

**Issue by mayankdtu** [jojohappy/zabbix-relay#4]
Hi I am receiving the following error when I try to get the historical data,
I am not good with node.js Can you confirm what it means?

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/home/mayank/zabbix-relay/node_modules/moment/moment.js:285:105)
    at configFromString (/home/mayank/zabbix-relay/node_modules/moment/moment.js:2015:32)
    at configFromInput (/home/mayank/zabbix-relay/node_modules/moment/moment.js:2375:13)
    at prepareConfig (/home/mayank/zabbix-relay/node_modules/moment/moment.js:2358:13)
    at createFromConfig (/home/mayank/zabbix-relay/node_modules/moment/moment.js:2325:44)
    at createLocalOrUTC (/home/mayank/zabbix-relay/node_modules/moment/moment.js:2412:16)
    at local__createLocal (/home/mayank/zabbix-relay/node_modules/moment/moment.js:2416:16)
    at utils_hooks__hooks (/home/mayank/zabbix-relay/node_modules/moment/moment.js:16:29)
    at cli (/home/mayank/zabbix-relay/lib/relay.js:83:18)
    at module.exports (/home/mayank/zabbix-relay/lib/relay.js:92:5)
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/home/mayank/zabbix-relay/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
    at Query.ErrorPacket (/home/mayank/zabbix-relay/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/mayank/zabbix-relay/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/mayank/zabbix-relay/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/mayank/zabbix-relay/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/mayank/zabbix-relay/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/home/mayank/zabbix-relay/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/mayank/zabbix-relay/node_modules/mysql/lib/Connection.js:214:25)
    at fetchTrends (/home/mayank/zabbix-relay/lib/task.js:43:41)
    at /home/mayank/zabbix-relay/lib/task.js:72:9
    at Array.forEach (native)
    at /home/mayank/zabbix-relay/lib/task.js:71:13
    at Client.<anonymous> (/home/mayank/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:27:9)
    at Client.<anonymous> (/home/mayank/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:66:5)
    at Request.self.callback (/home/mayank/zabbix-relay/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }

```

**Comment by jojohappy** [comment]
Can you give me your command? If the format of date is wrong, it will throw the exception. I think.

**Comment by layogm** [comment]
It worked fine later. I was giving some fields wrong. Thanks a lot for the help.
