### ISSUE TITLE
Problem during import data from Zabbix

### ISSUE THREAD

**Issue by kornikov** [jojohappy/zabbix-relay#5]
I've got an error during importing history from zabbix

TypeError: Cannot read property 'length' of undefined 
    at /home/systemsupport/zabbix-relay-master/lib/relay.js:38:37 
    at null.<anonymous> (/home/systemsupport/zabbix-relay-master/node_modules/zabbix-node/lib/zabbix.js:19:7) 
    at null.<anonymous> (/home/systemsupport/zabbix-relay-master/node_modules/zabbix-node/lib/zabbix.js:66:5) 
    at Request.self.callback (/home/systemsupport/zabbix-relay-master/node_modules/request/request.js:186:22) 
    at Request.emit (events.js:98:17) 
    at Request.<anonymous> (/home/systemsupport/zabbix-relay-master/node_modules/request/request.js:1081:10) 
    at Request.emit (events.js:95:17) 
    at IncomingMessage.<anonymous> (/home/systemsupport/zabbix-relay-master/node_modules/request/request.js:1001:12) 
    at IncomingMessage.g (events.js:180:16) 
    at IncomingMessage.emit (events.js:117:20) 

Any help?

**Comment by kornikov** [comment]
Zabbix 3.2

**Comment by jojohappy** [comment]
I can not replay this exception. Can you provide more information?

**Comment by kornikov** [comment]
What information is needed?

**Comment by jojohappy** [comment]
Please provide your running command and how many hosts belongs to the hostgroup of zabbix you specified.

**Comment by kornikov** [comment]
NODE_ENV=production nodejs server.js shell
I've tried to import data from several groups. From 7 то 35 hosts. Same error

**Comment by asivkov** [comment]
Have same issue as well for zabbix 2.4

cat config.production.js 
module.exports = {
  mysql: {
    host: 'localhost',
    user: 'zabbix',
    password: 'zabbix',
    database: 'zabbix',
    port: 3306
  },
  zabbix: {
    url: 'http://X.X.X.X/zabbix/api_jsonrpc.php',
    username: 'Admin',
    password: 'XXXXX'
  }
};

start relay

TypeError: Cannot read property 'length' of undefined
    at /opt/zabbix-relay/zabbix-relay/lib/relay.js:38:37
    at null.<anonymous> (/opt/zabbix-relay/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:19:7)
    at null.<anonymous> (/opt/zabbix-relay/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:66:5)
    at Request.self.callback (/opt/zabbix-relay/zabbix-relay/node_modules/request/request.js:186:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/opt/zabbix-relay/zabbix-relay/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/opt/zabbix-relay/zabbix-relay/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)

**Comment by asivkov** [comment]
And the command if needed:

NODE_ENV=production node server.js command -d elastic -g 'XXXXX' -l 5m -t 'history' -u 'ELKIP:Port'

**Comment by asivkov** [comment]
I have further debugged this and I had HTTP 503 in response from my proxy server. Once http_proxy env unset - no more such error. Though instead I have other one which I can't figure out so far (with some debugging info):

[root@hdm-puppet-master zabbix-relay]# NODE_ENV=production node server.js command -d elastic -g 'G_NAME' -l 5m -t 'history' -u 'ELKIP:PORT' 
start relay
{ url: 'http://localhost/zabbix/api_jsonrpc.php',
  user: 'Admin',
  password: 'Password',
  id: 0,
  auth: null }
zabbix api error: [object Object]
body [object Object]
resp [object Object]

**Comment by asivkov** [comment]
Sorry, debugged via tcpdump - was bad zabbix user pwd.
