### ISSUE TITLE
Error in importing trends to influxdb

### ISSUE THREAD

**Issue by kisienya** [jojohappy/zabbix-relay#6]
Hi,

Much appreciate this tool.
I have the following:

**Command**
NODE_ENV=production node server.js command -d influxdb -g 'Zabbix servers' -l 30m -t 'trends' -u 'root:'password'@localhost:8086/zabbix_servers'

**Result**
start relay
Total 1 hosts
/root/zabbix-relay/lib/adapter/influxdbAdapter.js:11
    host: result[3],
                ^

TypeError: Cannot read property '3' of null
    at new InfluxdbAdapter (/root/zabbix-relay/lib/adapter/influxdbAdapter.js:11:17)
    at /root/zabbix-relay/lib/relay.js:42:25
    at Array.forEach (native)
    at /root/zabbix-relay/lib/relay.js:41:25
    at .<anonymous> (/root/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:27:9)
    at .<anonymous> (/root/zabbix-relay/node_modules/zabbix-node/lib/zabbix.js:66:5)
    at Request.self.callback (/root/zabbix-relay/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/zabbix-relay/node_modules/request/request.js:1081:10)

Can I get some help..

Thanks

**Comment by kisienya** [comment]
Was able to solve the issue. I was using a complex password on the URI
'test:test@localhost:8086/mydb'
So I changed the regex on /root/zabbix-relay/lib/adapter/influxdbAdapter.js to allow for complex passwords. It worked.

Thanks

**Comment by jojohappy** [comment]
Do you change the regular expressions on the influxdbAdapter.js? But It is correct for the regular expressions and the URI (test:test@localhost:8086/mydb) you provide.  

The result is

**Comment by kisienya** [comment]
Actually, I have a complex password that includes spaces and special characters, that's why I needed to change the regex.

**Comment by jojohappy** [comment]
Thank you for your issues

I will fix this bug soon.
